### ISSUE TITLE
US Cata Classic Lua Errors

### ISSUE THREAD

**Issue by evilgodly** [Thaoky/Altoholic_Cata#1]
Getting these errors upon login to US Cata Classic

9x Altoholic/Locales/enUS.lua:4: attempt to index local 'L' (a nil value)
[string "@Altoholic/Locales/enUS.lua"]:4: in main chunk

Locals:
addonName = "Altoholic"
L = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "enUS"
(*temporary) = "attempt to index local 'L' (a nil value)"

9x Altoholic/Tooltip.lua:25: attempt to index local 'L' (a nil value)
[string "@Altoholic/Tooltip.lua"]:25: in main chunk

Locals:
addonName = "Altoholic"
addon = <table> {
 DATASTORE_GUILD_MAIL_RECEIVED = <function> defined @Altoholic/Comm.lua:430
 GetClassExtension = <function> defined @Altoholic/Templates/ClassExtensions.lua:43
 EmptyFunc = <function> defined @Altoholic/Core.lua:67
 OnInitialize = <function> defined @Altoholic/Core.lua:338
 Service = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:107
 Print = <function> defined @Altoholic/Core.lua:484
 BindViewToController = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:123
 SetClassExtensions = <function> defined @Altoholic/Templates/ClassExtensions.lua:48
 GetGuildMemberVersion = <function> defined @Altoholic/Core.lua:345
 RegisterClassExtensions = <function> defined @Altoholic/Templates/ClassExtensions.lua:37
 AccSharingHandler = <function> defined @Altoholic/Comm.lua:102
 TradeSkills = <table> {
 }
 Controller = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:187
 DATASTORE_GUILD_LEFT = <function> defined @Altoholic/Comm.lua:473
 Icons = <table> {
 }
 Helpers = <table> {
 }
 Version = "v4.4.001"
 Comm = <table> {
 }
 Colors = <table> {
 }
 DATASTORE_MAIL_EXPIRY = <function> defined @Altoholic/Comm.lua:466
 VersionNum = 404001
 UnbindViewFromController = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:169
 Tabs = <table> {
 }
 DATASTORE_GLOBAL_MAIL_EXPIRY = <function> defined @Altoholic/Comm.lua:436
}
colors = <table> {
 cyan = "|cFF1CFAFE"
 recipeOrange = "|cFFFF8040"
 Horde = "|cFFFF0000"
 Alliance = "|cFF2459FF"
 common = "|cFFFFFFFF"
 gold = "|cFFFFD700"
 classMage = "|cFF69CCF0"
 epic = "|cFFA335EE"
 orange = "|cFFFF7F00"
 red = "|cFFFF0000"
 rare = "|cFF0070DD"
 felGreen = "|cFFD6EB00"
 recipeGreen = "|cFF40C040"
 battleNetBlue = "|cff82c5ff"
 heirloom = "|cFFE6CC80"
 teal = "|cFF00FF9A"
 uncommon = "|cFF1EFF00"
 lightBlue = "|cFFB0B0FF"
 classHunter = "|cFFABD473"
 legendary = "|cFFFF8000"
 grey = "|cFF909090"
 green = "|cFF00FF00"
 darkred = "|cFFF00000"
 yellow = "|cFFFFFF00"
 recipeGrey = "|cFF808080"
 white = "|cFFFFFFFF"
}
L = nil
THIS_ACCOUNT = "Default"
THIS_REALM = "Mankrik"
storedLink = nil
options = nil
hearthstoneItemIDs = <table> {
 6948 = true
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'L' (a nil value)"

9x Altoholic/Tooltip.lua:25: attempt to index local 'L' (a nil value)
[string "@Altoholic/Tooltip.lua"]:25: in main chunk

Locals:
addonName = "Altoholic"
addon = <table> {
 DATASTORE_GUILD_MAIL_RECEIVED = <function> defined @Altoholic/Comm.lua:430
 GetClassExtension = <function> defined @Altoholic/Templates/ClassExtensions.lua:43
 EmptyFunc = <function> defined @Altoholic/Core.lua:67
 OnInitialize = <function> defined @Altoholic/Core.lua:338
 Service = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:107
 Print = <function> defined @Altoholic/Core.lua:484
 BindViewToController = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:123
 SetClassExtensions = <function> defined @Altoholic/Templates/ClassExtensions.lua:48
 GetGuildMemberVersion = <function> defined @Altoholic/Core.lua:345
 RegisterClassExtensions = <function> defined @Altoholic/Templates/ClassExtensions.lua:37
 AccSharingHandler = <function> defined @Altoholic/Comm.lua:102
 TradeSkills = <table> {
 }
 Controller = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:187
 DATASTORE_GUILD_LEFT = <function> defined @Altoholic/Comm.lua:473
 Icons = <table> {
 }
 Helpers = <table> {
 }
 Version = "v4.4.001"
 Comm = <table> {
 }
 Colors = <table> {
 }
 DATASTORE_MAIL_EXPIRY = <function> defined @Altoholic/Comm.lua:466
 VersionNum = 404001
 UnbindViewFromController = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:169
 Tabs = <table> {
 }
 DATASTORE_GLOBAL_MAIL_EXPIRY = <function> defined @Altoholic/Comm.lua:436
}
colors = <table> {
 cyan = "|cFF1CFAFE"
 recipeOrange = "|cFFFF8040"
 Horde = "|cFFFF0000"
 Alliance = "|cFF2459FF"
 common = "|cFFFFFFFF"
 gold = "|cFFFFD700"
 classMage = "|cFF69CCF0"
 epic = "|cFFA335EE"
 orange = "|cFFFF7F00"
 red = "|cFFFF0000"
 rare = "|cFF0070DD"
 felGreen = "|cFFD6EB00"
 recipeGreen = "|cFF40C040"
 battleNetBlue = "|cff82c5ff"
 heirloom = "|cFFE6CC80"
 teal = "|cFF00FF9A"
 uncommon = "|cFF1EFF00"
 lightBlue = "|cFFB0B0FF"
 classHunter = "|cFFABD473"
 legendary = "|cFFFF8000"
 grey = "|cFF909090"
 green = "|cFF00FF00"
 darkred = "|cFFF00000"
 yellow = "|cFFFFFF00"
 recipeGrey = "|cFF808080"
 white = "|cFFFFFFFF"
}
L = nil
THIS_ACCOUNT = "Default"
THIS_REALM = "Mankrik"
storedLink = nil
options = nil
hearthstoneItemIDs = <table> {
 6948 = true
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'L' (a nil value)"

9x Altoholic/Altoholic.lua:668: attempt to index upvalue 'L' (a nil value)
[string "@Altoholic/Altoholic.lua"]:668: in function `OnTimeToNextWarningChanged'
[string "*TabOptions.xml:252_OnValueChanged"]:1: in function <[string "*TabOptions.xml:252_OnValueChanged"]:1>

Locals:
self = <table> {
 DATASTORE_GUILD_MAIL_RECEIVED = <function> defined @Altoholic/Comm.lua:430
 SetItemButtonTexture = <function> defined @Altoholic/Altoholic.lua:424
 UnbindViewFromController = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:169
 GetMoneyStringShort = <function> defined @Altoholic/Altoholic.lua:515
 OnInitialize = <function> defined @Altoholic/Core.lua:338
 BindViewToController = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:123
 GetMoneyString = <function> defined @Altoholic/Altoholic.lua:494
 SetupOptions = <function> defined @Altoholic/Frames/TabOptions.lua:147
 UpdateMyMemoryUsage = <function> defined @Altoholic/Frames/TabOptions.lua:410
 FormatDelay = <function> defined @Altoholic/Altoholic.lua:562
 RestoreOptionsToUI = <function> defined @Altoholic/Frames/TabOptions.lua:344
 SetLastAccountSharingInfo = <function> defined @Altoholic/Altoholic.lua:87
 OnUpdate = <function> defined @Altoholic/Frames/TabOptions.lua:435
 AccSharingHandler = <function> defined @Altoholic/Comm.lua:102
 ToggleOption = <function> defined @Altoholic/Frames/TabOptions.lua:137
 ToggleUI = <function> defined @Altoholic/Altoholic.lua:343
 OnShow = <function> defined @Altoholic/Altoholic.lua:351
 GetFirstDayOfWeek = <function> defined @Altoholic/Altoholic.lua:719
 Controller = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:187
 Item_OnEnter = <function> defined @Altoholic/Altoholic.lua:386
 Helpers = <table> {
 }
 SaveUnsafeItem = <function> defined @Altoholic/Altoholic.lua:724
 Equipment = <table> {
 }
 GetLastAccountSharingInfo = <function> defined @Altoholic/Altoholic.lua:93
 Tabs = <table> {
 }
 DDM_Initialize = <function> defined @Altoholic/Altoholic.lua:675
 VersionNum = 404001
 SetFirstDayOfWeek = <function> defined @Altoholic/Altoholic.lua:715
 DATASTORE_GUILD_LEFT = <function> defined @Altoholic/Comm.lua:473
 DATASTORE_GLOBAL_MAIL_EXPIRY = <function> defined @Altoholic/Comm.lua:436
 OnTimeToNextWarningChanged = <function> defined @Altoholic/Altoholic.lua:663
 GetClassExtension = <function> defined @Altoholic/Templates/ClassExtensions.lua:43
 EmptyFunc = <function> defined @Altoholic/Core.lua:67
 GetCharacterTable = <function> defined @Altoholic/Altoholic.lua:73
 UpdateSlider = <function> defined @Altoholic/Altoholic.lua:648
 Comm = <table> {
 }
 Print = <function> defined @Altoholic/Core.lua:484
 GetTimeString = <function> defined @Altoholic/Altoholic.lua:548
 GetSpellIDFromRecipeLink = <function> defined @Altoholic/Altoholic.lua:479
 GetRecipeLevel = <function> defined @Altoholic/Altoholic.lua:605
 SetClassExtensions = <function> defined @Altoholic/Templates/ClassExtensions.lua:48
 GetGuildMemberVersion = <function> defined @Altoholic/Core.lua:345
 ShowWidgetTooltip = <function> defined @Altoholic/Altoholic.lua:654
 RegisterClassExtensions = <function> defined @Altoholic/Templates/ClassExtensions.lua:37
 GetRecipeLink = <function> defined @Altoholic/Altoholic.lua:485
 ListCharsOnQuest = <function> defined @Altoholic/Altoholic.lua:634
 GetIDFromLink = <function> defined @Altoholic/Altoholic.lua:470
 GetSpellIcon = <function> defined @Altoholic/Altoholic.lua:466
 TradeSkills = <table> {
 }
 ItemFilters = <table> {
 }
 GetSuggestion = <function> defined @Altoholic/Altoholic.lua:595
 Item_OnClick = <function> defined @Altoholic/Altoholic.lua:40

9x Altoholic/Frames/MinimapButton.lua:23: attempt to index upvalue 'L' (a nil value)
[string "@Altoholic/Frames/MinimapButton.lua"]:23: in function `OnBind'
[string "@Altoholic/Libs/LibMVC-1.0-4/LibMVC.lua"]:165: in function `BindViewToController'
[string "*MinimapButton.xml:10_OnLoad"]:1: in function <[string "*MinimapButton.xml:10_OnLoad"]:1>

Locals:
frame = AltoholicMinimapButton {
 0 = <userdata>
 Button_OnClick = <function> defined @Altoholic/Frames/MinimapButton.lua:41
 Move = <function> defined @Altoholic/Frames/MinimapButton.lua:26
 OnBind = <function> defined @Altoholic/Frames/MinimapButton.lua:21
 Icon = Texture {
 }
 Update = <function> defined @Altoholic/Frames/MinimapButton.lua:32
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = "%s

%s%s
%s%s"
(*temporary) = "Altoholic"
(*temporary) = "|cFFFFFFFF"
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index upvalue 'L' (a nil value)"
addonName = "Altoholic"
colors = <table> {
 cyan = "|cFF1CFAFE"
 recipeOrange = "|cFFFF8040"
 Horde = "|cFFFF0000"
 Alliance = "|cFF2459FF"
 common = "|cFFFFFFFF"
 gold = "|cFFFFD700"
 classMage = "|cFF69CCF0"
 epic = "|cFFA335EE"
 orange = "|cFFFF7F00"
 red = "|cFFFF0000"
 rare = "|cFF0070DD"
 felGreen = "|cFFD6EB00"
 recipeGreen = "|cFF40C040"
 battleNetBlue = "|cff82c5ff"
 heirloom = "|cFFE6CC80"
 teal = "|cFF00FF9A"
 uncommon = "|cFF1EFF00"
 lightBlue = "|cFFB0B0FF"
 classHunter = "|cFFABD473"
 legendary = "|cFFFF8000"
 grey = "|cFF909090"
 green = "|cFF00FF00"
 darkred = "|cFFF00000"
 yellow = "|cFFFFFF00"
 recipeGrey = "|cFF808080"
 white = "|cFFFFFFFF"
}
L = nil

9x Altoholic/Frames/AccountSharing.lua:157: attempt to index local 'L' (a nil value)
[string "@Altoholic/Frames/AccountSharing.lua"]:157: in main chunk

Locals:
addonName = "Altoholic"
addon = <table> {
 DATASTORE_GUILD_MAIL_RECEIVED = <function> defined @Altoholic/Comm.lua:430
 SetItemButtonTexture = <function> defined @Altoholic/Altoholic.lua:424
 UnbindViewFromController = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:169
 GetMoneyStringShort = <function> defined @Altoholic/Altoholic.lua:515
 OnInitialize = <function> defined @Altoholic/Core.lua:338
 GetSpellIcon = <function> defined @Altoholic/Altoholic.lua:466
 BindViewToController = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:123
 GetMoneyString = <function> defined @Altoholic/Altoholic.lua:494
 SetupOptions = <function> defined @Altoholic/Frames/TabOptions.lua:147
 UpdateMyMemoryUsage = <function> defined @Altoholic/Frames/TabOptions.lua:410
 FormatDelay = <function> defined @Altoholic/Altoholic.lua:562
 RestoreOptionsToUI = <function> defined @Altoholic/Frames/TabOptions.lua:344
 SetLastAccountSharingInfo = <function> defined @Altoholic/Altoholic.lua:87
 OnUpdate = <function> defined @Altoholic/Frames/TabOptions.lua:435
 AccSharingHandler = <function> defined @Altoholic/Comm.lua:102
 ToggleOption = <function> defined @Altoholic/Frames/TabOptions.lua:137
 ToggleUI = <function> defined @Altoholic/Altoholic.lua:343
 OnShow = <function> defined @Altoholic/Altoholic.lua:351
 GetFirstDayOfWeek = <function> defined @Altoholic/Altoholic.lua:719
 Controller = <function> defined @Altoholic/Libs/LibMVC-1.0/LibMVC.lua:187
 Item_OnEnter = <function> defined @Altoholic/Altoholic.lua:386
 Helpers = <table> {
 }
 SaveUnsafeItem = <function> defined @Altoholic/Altoholic.lua:724
 Equipment = <table> {
 }
 GetLastAccountSharingInfo = <function> defined @Altoholic/Altoholic.lua:93
 Tabs = <table> {
 }
 DDM_Initialize = <function> defined @Altoholic/Altoholic.lua:675
 VersionNum = 404001
 SetFirstDayOfWeek = <function> defined @Altoholic/Altoholic.lua:715
 DATASTORE_GUILD_LEFT = <function> defined @Altoholic/Comm.lua:473
 DATASTORE_GLOBAL_MAIL_EXPIRY = <function> defined @Altoholic/Comm.lua:436
 OnTimeToNextWarningChanged = <function> defined @Altoholic/Altoholic.lua:663
 GetClassExtension = <function> defined @Altoholic/Templates/ClassExtensions.lua:43
 EmptyFunc = <function> defined @Altoholic/Core.lua:67
 GetCharacterTable = <function> defined @Altoholic/Altoholic.lua:73
 UpdateSlider = <function> defined @Altoholic/Altoholic.lua:648
 Comm = <table> {
 }
 Print = <function> defined @Altoholic/Core.lua:484
 GetTimeString = <function> defined @Altoholic/Altoholic.lua:548
 GetSpellIDFromRecipeLink = <function> defined @Altoholic/Altoholic.lua:479
 GetRecipeLevel = <function> defined @Altoholic/Altoholic.lua:605
 SetClassExtensions = <function> defined @Altoholic/Templates/ClassExtensions.lua:48
 GetGuildMemberVersion = <function> defined @Altoholic/Core.lua:345
 ShowWidgetTooltip = <function> defined @Altoholic/Altoholic.lua:654
 RegisterClassExtensions = <function> defined @Altoholic/Templates/ClassExtensions.lua:37
 GetRecipeLink = <function> defined @Altoholic/Altoholic.lua:485
 ListCharsOnQuest = <function> defined @Altoholic/Altoholic.lua:634
 GetIDFromLink = <function> defined @Altoholic/Altoholic.lua:470
 Sharing = <table> {
 }
 TradeSkills = <table> {
 }
 ItemFilters = <table> {
 }
 GetSuggestion = <function> defined @Altoholic/Altoholic.lua:595
 Item_OnClick = <function> def

**Comment by Thaoky** [comment]
The official Cataclysm release has now been done, this is from an older version not yet fully compatible with Cataclysm.
