### ISSUE TITLE
Addon not listed with Curse wow_cata

### ISSUE THREAD

**Issue by Nancara** [Thaoky/Altoholic_Cata#2]
There was a message to delete the files when I logged in to a character. I did and now there is no files in Curse Classic Cata for the addon. It no longer exists in there. Before I removed the files the addon was showing as out of date. Thanks I love this addon.

**Comment by evilgodly** [comment]
> There was a message to delete the files when I logged in to a character. I did and now there is no files in Curse Classic Cata for the addon. It no longer exists in there. Before I removed the files the addon was showing as out of date. Thanks I love this addon.

it is still on the CurseForge website directly but due to it had yet to be updated on their it is not listed in the Desktop App anymore. Even if you download the files here from GitHub it still wont be listed in the Desktop App.

**Comment by fostermatt** [comment]
I tried commenting on Curse but the posting fails everytime so trying here. Is this not supposed to show max level characters or something? I can't get my main or any max level alts to show up in the activity section. I just want to know if I need to check mail on an alt but it just doesn't work.

**Comment by evilgodly** [comment]
> I tried commenting on Curse but the posting fails everytime so trying here. Is this not supposed to show max level characters or something? I can't get my main or any max level alts to show up in the activity section. I just want to know if I need to check mail on an alt but it just doesn't work.

Have you gone to the discord channel > cata bug part and followed the pined comments?

**Comment by Thaoky** [comment]
The official Cataclysm release has now been done, this is from an older version not yet fully compatible with Cataclysm.
